<a href="https://colab.research.google.com/github/anjoomnaved/Pedulum-Dynamics-Linearization/blob/main/numpy_contd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np

In [55]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f78f8b3c550>)

In [56]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [57]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [58]:
weights = np.array([0.3, 0.2, 0.5])

In [59]:
yields = climate_data @ weights

In [60]:
yields #row vector

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [61]:
yields.shape

(10000,)

In [62]:
yields=yields.reshape(10000,1) #converted to column vector basically 

In [63]:
yields

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [64]:
climate_results=np.concatenate((climate_data,yields),axis=1)

In [65]:
climate_results #got a fourth coulumn  using concatenate function

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [66]:
climate_results.shape

(10000, 4)

In [67]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temp,rainfall,humidity,yield_apples',
           comments='')

In [68]:
import os

In [42]:
os.listdir('.')

['.config', 'climate.txt', 'climate_results.txt', 'sample_data']

AttributeError: ignored

In [51]:
# Install the library
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 6.0 MB/s 


In [69]:
import jovian

In [70]:
jovian.commit()

[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab
